on:
  workflow_dispatch:
name: Update support to arm
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          python update.py
          git config --global user.name 'Darlekesh'
          git config --global user.email 'darlekesh@users.noreply.github.com'
          git commit -am "Automated report"
          git push
  
